name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
  security-events: write
  artifact-metadata: write

jobs:
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml

  build-image:
    name: Build Image
    needs: build-and-test
    uses: the-most-secure-supply-chain-ever-maaan/workflows/.github/workflows/build.yaml@eca4c1fc0dbd0f19943029aeca7fb1302a20a8d1 # 1.5.0
    secrets:
      deploy-repo-token: ${{ secrets.CLUSTER_CONFIG_TOKEN }}
